name: Clean Caches

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  clean-caches:
    name: Clean Caches
    permissions:
      contents: read
    uses: JackPlowman/reusable-workflows/.github/workflows/common-clean-caches.yml@302833d53c3a6827fe433f01b624873b09b0cc94 # v2026.03.16.01
    secrets:
      workflow_github_token: ${{ secrets.GH_TOKEN }}
