name: Clean Caches

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  clean-caches:
    name: Clean Caches
    permissions:
      contents: read
    uses: JackPlowman/reusable-workflows/.github/workflows/common-clean-caches.yml@c753ad4efc9afb1a0efbe8d4e7bb0a9039e8f0e5 # v2026.03.22.01
    secrets:
      workflow_github_token: ${{ secrets.GH_TOKEN }}
