# Visit https://github.com/lowlighter/metrics#-documentation for full reference

name: Metrics

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:
  push:
    branches: "main"

permissions:
  contents: write

jobs:
  github-metrics:
    name: GitHub Metrics
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@v3.34
        with:
          # Size
          config_display: large
          # Configuration of Metrics
          user: JackPlowman
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/London
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 30
          plugin_habits_facts: yes
          plugin_habits_from: 1000
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          # Git Configuration
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_message: "Update GitHub metrics"
          output_condition: data-changed
