# Visit https://github.com/lowlighter/metrics#-documentation for full reference

name: Metrics

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
  push:
    branches: ["main"]

permissions: {}

jobs:
  github-metrics:
    name: GitHub Metrics
    runs-on: ubuntu-latest
    permissions:
      contents: write # For committing the updated SVG file
    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@65836723097537a54cd8eb90f61839426b4266b6 # v3.34
        with:
          # Size
          config_display: large
          # Configuration of Metrics
          user: JackPlowman
          template: classic
          base: header, activity, community, repositories, metadata
          base_indepth: yes
          repositories_batch: 1000
          config_timezone: Europe/London
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 10
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 365
          plugin_languages_recent_load: 1000
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_languages_ignored: JSON, YAML, Markdown
          # Git Configuration
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_message: "Update GitHub metrics"
          output_condition: data-changed
