name: "Pull Request Tasks"

on:
  pull_request:
    types: [opened, edited, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  common-pull-request-tasks:
    name: Common Pull Request Tasks
    permissions:
      pull-requests: write # For writing labels and comments on PRs
    uses: JackPlowman/reusable-workflows/.github/workflows/common-pull-request-tasks.yml@c753ad4efc9afb1a0efbe8d4e7bb0a9039e8f0e5 # v2026.03.22.01
    secrets:
      workflow_github_token: ${{ secrets.GITHUB_TOKEN }}
